name: PocketMine-MP Crowdin upload

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch name
        required: true
        type: string
  repository_dispatch:
    types: pocketmine_mp_crowdin_upload

jobs:
  upload:
    name: Upload base strings
    runs-on: ubuntu-latest

    steps:
      - name: Get branch name
        id: branch
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "branch=${{ github.event.inputs.branch }}" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == "repository_dispatch" ]]; then
            echo "branch=${{ github.event.client_payload.branch }}" >> $GITHUB_OUTPUT
          else
            echo "::error Unexpected event type ${{ github.event_name }}"
            exit 1
          fi
  
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/PocketMine-MP # to allow testing on forks without editing the workflow
          ref: ${{ steps.branch.outputs.branch }}

      - name: Preprocess eng.ini placeholders so Crowdin can understand them
        working-directory: resources/translations
        run: |
          sed -i -r 's/\{%([A-Za-z0-9]+)\}/\{\1\}/g' eng.ini
          cat eng.ini

      - name: Upload eng.ini to Crowdin
        uses: crowdin/github-action@v2
        with:
          upload_sources: true
          upload_translations: false
          download_translations: false
          create_pull_request: false
          crowdin_branch_name: ${{ steps.branch.outputs.branch }}
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
